### ISSUE TITLE
Fresh clone fails on npm install

### ISSUE THREAD

**Issue by marcusoftnet** [ActionableAgile/jira-to-analytics#53]
Hi, 

I made a fork of your code and clone it. 

Then I went `npm i` (install for short) and got the following error message. 

``` bash
› npm i

> thread-sleep@1.0.4 install /Users/marcus/Projects/jira-to-analytics/node_modules/thread-sleep
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/Users/marcus/.nvm/versions/node/v9.11.1/bin/node',
node-pre-gyp verb cli   '/Users/marcus/Projects/jira-to-analytics/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.9
node-pre-gyp info using node@9.11.1 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Users/marcus/Projects/jira-to-analytics/node_modules/thread-sleep/lib/binding/Release/node-v59-darwin-x64/thread_sleep.node" (not found)
node-pre-gyp http GET https://node-pre-gyp-forbeslindesay.s3.amazonaws.com/thread_sleep/v1.0.4/Release/thread_sleep-v1.0.4-node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: Cannot find module 'internal/util/types'
node-pre-gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
node-pre-gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:598:17)
node-pre-gyp ERR! stack     at require (internal/modules/cjs/helpers.js:11:18)
node-pre-gyp ERR! stack     at evalmachine.<anonymous>:31:26
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/marcus/Projects/jira-to-analytics/node_modules/thread-sleep/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/fs.js:11:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:654:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:566:32)
node-pre-gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/Users/marcus/.nvm/versions/node/v9.11.1/bin/node" "/Users/marcus/Projects/jira-to-analytics/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/marcus/Projects/jira-to-analytics/node_modules/thread-sleep
node-pre-gyp ERR! node -v v9.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>

> spawn-sync@1.0.15 postinstall /Users/marcus/Projects/jira-to-analytics/node_modules/spawn-sync
> node postinstall

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> actionableagileimporttool@1.1.0 prepublish /Users/marcus/Projects/jira-to-analytics
> npm run build


> actionableagileimporttool@1.1.0 build /Users/marcus/Projects/jira-to-analytics
> tsc

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN actionableagileimporttool@1.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: thread-sleep@1.0.4 (node_modules/thread-sleep):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 7

added 342 packages in 24.681s
```

I'm on Node 9.11.0 - any idea on why this is not working?

**Comment by johnrjj** [comment]
Please try using yarn, as that is the package manager we use during development.

**Comment by marcusoftnet** [comment]
Yes that was it! 

Thanks @johnrjj
